name: in_app_permission
description: "Permission plugin for Flutter. This plugin provides a cross-platform (iOS, Android) API to request and check permissions."
version: 1.1.0
repository: https://github.com/Mohiuddin655-PUB/in_app_permission.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: